### ISSUE TITLE
Add Min and Max operators

### ISSUE THREAD

**Issue by bstordrup** [HelloKitty/Generic.Math#1]
System.Math contains Min and Max operators - these are not found in Generic.Math.

Instead of making the logic in client code, they could be added to Generic.Math.

**Comment by HelloKitty** [comment]
@bstordrup sounds like a good idea! Unfortunately this library only exists to mirror the functionality of Jon Skeet's MiscUtil generic math API which, long ago, temporarily wasn't fully functional for all versions of netstandard during the turblent time of netstandard1.1-netstandard2.0. So this library fits its purpose and may no longer have much of a use compared to MiscUtil in modern .NET since those turblent times are over. MiscUtils probably works for netstandard/netcore nowadays I'd guess.

No updates are planned and the library serves its orignially minimally scoped purpose of being an old .netstandard/core compatible fork of Jon Skeet's MiscUtil generic math API.
